var express = require('express');
var app = express.Router();
var UserModel=require('../models/profile');

app.get('/',function(req,res){
    console.log("Working");
});

//signup scenario
app.post('/newuser',function(req,res){
    console.log(req.body.firstName);
    var autoGeneratedPassword=generatePassword();
    var user = new UserModel({
        firstName:req.body.firstName,
        lastName:req.body.lastName,
        userName:req.body.userName,
        contactNumber:req.body.contact,
        userRole:'Blogger',
        emailId:req.body.email,
        birthDate:req.body.birthDate,
        password:autoGeneratedPassword
    })

    user.save((err,user)=>{
        if(err){
            res.send(err).status(501);
        }
        else{
            res.send(user).status(200);
        }
    })
});

//genearte random password
function generatePassword() {
    var length = 8,
        charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
        retVal = "";
    for (var i = 0, n = charset.length; i < length; ++i) {
        retVal += charset.charAt(Math.floor(Math.random() * n));
    }
    return retVal;
}

//login scenario
app.post('/existingUser',(req,res)=>{
    //UserModel.findOne({emailId:req.body.userEmail},function(err,user){
    UserModel.findOne({$or:[{emailId:req.body.userEmail},{userName:req.body.userEmail}]},function(err,user){    
        if(err){
            res.send(err).status(501);
        }
        else{
            if(user.password==req.body.password){
                res.json({"message":"LoggedIn Sucessfully",data:user});
            }
            else{
                res.json({"message":"Password Mismatch"});
            }
        }
    })
});

module.exports = app;